#ifndef gtkmmphotobrowser_h
#define gtkmmphotobrowser_h

// Gtkmm headers
#include <gtkmm.h>

// Diesel headers
#include "diesel.h"
#include "gtkmmopenglview.h"
#include "gtkmmscrollbar.h"

namespace diesel
{
  class cGtkmmPhotoBrowser
  {
  public:
    friend class cGtkmmOpenGLView;
    friend class cGtkmmScrollBar;

    cGtkmmPhotoBrowser();

    void Init(int argc, char** argv);

    const Gtk::Widget& GetWidget() const;
    Gtk::Widget& GetWidget();

    bool IsOpenGLViewFocus() const;

  protected:
    // Events generated by the scrollbar
    void OnScrollBarScrolled(const cGtkmmScrollBar& widget);

    // Events generated by the OpenGL view
    void OnOpenGLViewContentChanged();
    void OnOpenGLViewScrollTop();
    void OnOpenGLViewScrollBottom();
    void OnOpenGLViewScrollPageUp();
    void OnOpenGLViewScrollPageDown();

  private:
    bool event_box_key_press(GdkEventKey* pEvent);
    bool event_box_button_press(GdkEventButton* pEvent);
    bool event_box_button_release(GdkEventButton* pEvent);
    bool event_box_scroll(GdkEventScroll* pEvent);
    bool event_box_motion_notify(GdkEventMotion* pEvent);

    cGtkmmOpenGLView openglView;

    cGtkmmScrollBar scrollBar;

    Gtk::EventBox eventBoxOpenglView;

    Gtk::HBox boxPhotoView;
  };
}

#endif // gtkmmphotobrowser_h
